### ISSUE TITLE
Integrate Bookstack import to LB

### ISSUE THREAD

**Issue by maggie0002** [LearnersBlock/learners-block#36]
Requirements:

- [ ] Create download panel available in the Settings page for downloading from the Makerspace:
   1. Reads self-hosted Bookstack API 
   2. If API returns list of shelves then populate a navigable page of its contents with PDF and HTML download links. 
   3. If download link is clicked then call appropriate API using the appropriate item id: `https://bookstack.learnersblock.org/bookstack/api/books/{id}/export/pdf` and send the URL to the Controller for download to the MakerSpace directory. 
 
- [ ] Alternatively, integrate a 'Send to Device' button into BookStack, so users can browse and benefit from the normal interface, but have the option to send items directly to their devices.

- [ ] Alternatively, a key could be added to each page, that can be copied and pasted into the settings panel to download that particular resource. 

<img width="1393" alt="Screenshot 2020-12-13 at 15 28 23" src="https://user-images.githubusercontent.com/64841595/102027299-04178a00-3d58-11eb-86ba-e96edc865906.png">

Docker Compose file to try it out locally:

```
version: '2'
services:
  mysql:
    image: mysql:5.7.31
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:0.30.4
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - "8080:8080"

volumes:
 mysql-data:
 uploads:
 storage-uploads:
```

Visit http://localhost:8080 . You can login with username 'admin@admin.com' and password 'password'.
